### PR TITLE
NFC support

### LINKED ISSUE #288: Can NFC be supported?
Can NFC be supported?

### PR DESCRIPTION
**Pull request by mateosilguero**
# Summary

This Close: #288 

NFC Support

## Test Plan

Screenshot_1570411131
Simulator Screen Shot - iPhone X - 2019-10-06 at 22 19 16

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by zoontek** [comment]
@mateosilguero Thanks! Otherwise, I made a quick check and it does not seems that NFC is a permission.

1) It is not requestable (doesn't need consent from the user).
2) It is not revokable (does not appears in app settings, neither on iOS or Android).

Screenshot 2019-10-07 at 13 44 35

It looks more like feature detection for me (a simple if to check if it's available). So it does not really make sense in this library.

**Comment by mateosilguero** [comment]
I'm agree with you, i couldnt find methods to request for permission, but it tells me if NFC is or not available

**Comment by mikehardy** [comment]
This appears to be the location for NFC stuff for react-native https://github.com/whitedogg13/react-native-nfc-manager - if it doesn't have the API you want they might love the contribution...

**Comment by zoontek** [comment]
Agreed with @mikehardy.
A PR to export this method https://github.com/whitedogg13/react-native-nfc-manager/blob/master/ios/NfcManager.m#L7 will be more logical.

**Comment by mateosilguero** [comment]
It make sense to have the isAvailable method on ios too ?

**Comment by zoontek** [comment]
@mateosilguero On react-native-nfc-manager yes

**Pull request closed without merging**
