### PR TITLE
Added notification support for Android

### PR DESCRIPTION
**Pull request by jbpin**
All is in the title ;)

### CODE REVIEW

**Comment by zifeo** [comment]
@yonahforst Any update on this :) ?

**Comment by yonahforst** [comment]
@jbpin @zifeo - I'm not sure about this... this isn't a standard permission in the sense that you can only check if it's been blocked, but you can't explicitly request it. I'm open to including it if you can find a nice way to explain this in the readme :))

**Comment by jasongaare** [comment]
@yonahforst I'm all for this. I was just about to do a PR myself for this very feature. 

I'm checking permissions for 'notification' on iOS to determine if I can send notifications, and it's annoying to need to write my own bridge just to check `areNotificationsEnabled` on Android.

I see you point about how you cannot 'request' this permission - but checking if the user has it 'authorized' or 'denied' would be super useful and easy to document

**Comment by yonahforst** [comment]
merged!

**Pull request merged**
