### PR TITLE
Support React Native 0.48

### PR DESCRIPTION
**Pull request by huhuanming**
Fix errors like`Duplicate interface definition for class 'RCTConvert'` .

### CODE REVIEW

**Comment by huhuanming** [comment]
@yonahforst

**Comment by huhuanming** [comment]
@yonahforst

**Comment by MoOx** [comment]
https://github.com/yonahforst/react-native-permissions/pull/138#issuecomment-329737303

**Comment by iegik** [comment]
> That proposal and work is about .h files, not .m or .mm files.

Notice about that comment: https://github.com/facebook/react-native/pull/15784#issuecomment-328306651

**Comment by yonahforst** [comment]
closed in favor of #146

**Pull request closed without merging**
