### PR TITLE
call request authorization on main thread

### PR DESCRIPTION
**Pull request by rpopovici**
call request authorization on main thread and ignore the first call for didChangeAuthorization

### CODE REVIEW

**Comment by yonahforst** [comment]
@rpopovici thanks for the PR. I had forgotten to commit and push this update: https://github.com/yonahforst/react-native-permissions/commit/040352cee096f2c98e7fda5252bb5c80de159a97

That should bring requestAuthorization to the main thread. If that fixes it, can you update the PR with just 'ignore the first call for didChangeAuthorization' and i'll merge it.

**Comment by rpopovici** [comment]
@yonahforst done!

**Comment by yonahforst** [comment]
merged! thanks @rpopovici !

**Comment by rpopovici** [comment]
welcome

**Pull request merged**
