### PR TITLE
Extract AsyncStorage from react native core

### LINKED ISSUE #300: Async Storage has been extracted from react-native core
### Describe your environment

* React-Native: 0.59.1
* Platform: Android
* Device: Physical (OnePlus 5)
* OS: 9 (Pie)
* react-native-permissions: 1.1.1
* Devtools: VSCode

### How to repeat issue and example

Getting this warning when used `react-native-permissions` to check for permissions:

```
Warning: Async Storage has been extracted from react-native core and will be removed in 
a future release. It can now be installed and imported from 
'@react-native-community/async-storage' instead of 'react-native'. See
https://github.com/react-native-community/react-native-async-storage
```

### Solution

Importing AsyncStorage from new `@react-native-community/async-storage`

### PR DESCRIPTION
**Pull request by ghost**
Fixes #300.

### CODE REVIEW

**Comment by ghost** [comment]
@zoontek I know this change is not that critical but it will be better the earlier. And it is not breaking anything.

**Comment by mcgloneleviROOT** [comment]
Please merge this.

**Comment by cormander** [comment]
I can confirm that this doesn't break anything. Am using this diff with patch-package while I wait for merge.

**Comment by mgpepe** [comment]
Another request to merge here

**Comment by william-normann** [comment]
AsyncStorage is a native library, it's not enough to complete make AsyncStorage available in this PR

**Comment by ghost** [comment]
@thuan-nguyen-js , didnt get you. Can you explain.

**Comment by william-normann** [comment]
Screen Shot 2019-07-03 at 6 21 25 PM

I suggest for a completed installation, or move AsyncStorage to peerDependencies

**Comment by ghost** [comment]
I think moving it to peerDependencies is better. Mostly all projects already depend on `AsyncStorage` so should not be an issue.

**Comment by mvanroon** [comment]
@sulaysumaria I don't this assumption should be made. This package depends on `@react-native-community/async-storage` so it should be treated as a such. I think this PR should include instructions  on how to install it or link to `@react-native-community/async-storage`'s README.md.

**Comment by ghost** [comment]
@mvanroon , Agreed.

But right now, `@react-native-community/async-storage` is a dependency not a peerDependency, thus no instructions are required.

Also to note: this PR is 3 months old now and `@react-native-community/async-storage` has also updated since creation of this PR.

**Comment by markrickert** [comment]
I agree with @mvanroon that instructions for linking the new community async storage should be provided as an optional step for documentation completeness.

**Comment by allthetime** [comment]
Please merge this. This library shouldn't be throwing warnings.

**Comment by zoontek** [comment]
It's now available in the 1.2.0! Please check the changelog https://github.com/react-native-community/react-native-permissions/releases/tag/1.2.0

I choose to go with a peer dependencies to keep RN 0.60 autolinking

**Pull request closed without merging**
