### PR TITLE
Fix RN import priority, favoring newest version of RN (Adds to #138 and #139)

### PR DESCRIPTION
**Pull request by TikiTDO**
Fixes imports for iOS files in RN 0.48 and newer, similar to #138 and #139, but with a more consistent and backwards compatible style.

### CODE REVIEW

**Comment by MoOx** [comment]
https://github.com/yonahforst/react-native-permissions/pull/138#issuecomment-329737303

**Review by hugo-retro — APPROVED** [review]

**Comment by zoontek** [comment]
@yonahforst Any ETA on this? Do you need some collaborators?

**Comment by dotansimha** [comment]
Any chance to merge it soon?

**Comment by vitorebatista** [comment]
Please, merge it asap.

**Comment by kelset** [comment]
@yonahforst can you get this merged and release a new version?

In the meantime, this fix is usable by writing, in `package.json`:

```js
    "react-native-permissions": "TikiTDO/react-native-permissions#008bc68",
```

**Comment by yonahforst** [comment]
@TikiTDO - thanks for this PR!

@everyone - I'm not actively working on any RN projects right now, so it's hard to find time to maintain this lib. If anyone is interested in collaborating, please let me know.

**Comment by kelset** [comment]
@yonahforst I know how you feel, I wish I had time to dedicate to it :(
Maybe ping the guys from the [React Community](https://github.com/react-community/) if they can take this over?

---
btw ETA for new release with this fix? 😇

**Comment by zoontek** [comment]
@yonahforst I'm interested. I work with RN everyday, and already a collaborator on react-native-i18 :)
I've done https://github.com/react-community/react-native-languages too

**Comment by MoOx** [comment]
I can help too. I think this package is widely used and need more love :)

**Comment by Obooman** [comment]
Hi there, when will this pr be released to npm?

**Pull request merged**
