### PR TITLE
fix for breaking iOS header change in RN 0.40.0

### PR DESCRIPTION
**Pull request by danieldkim**
For the breaking "iOS native headers moved" [change in RN  0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0).  Addresses facebook/react-native#11725.

### CODE REVIEW

**Comment by joncursi** [comment]
👍 

For anyone waiting on this, I created a temporary, forked version of this repo here: https://github.com/joncursi/react-native-permissions

Add it to package.json with:

```
    "react-native-permissions": "git+ssh://git@github.com/joncursi/react-native-permissions.git",
```

**Comment by ericnograles** [comment]
Thanks for the interim fix, @danieldkim and @joncursi, most helpful indeed!

@yonahforst any chance we can get this fix on the release plan?  It's a bummer that 0.40 kinda broke the ecosystem.  😞

**Comment by lucianomlima** [comment]
@yonahforst please merge this PR.

**Comment by yonahforst** [comment]
merged! thank you everyone, and thanks for your patience.

**Comment by danieldkim** [comment]
Thanks @yonahforst!

**Comment by joncursi** [comment]
@yonahforst will you be pushing up a new version to NPM soon, or should I be installing directly from github > master?

**Comment by joncursi** [comment]
0.2.6 is now on NPM, I'd recommend everyone converge back on that as opposed to the forked copies. I may actually end up removing my fork from GitHub since it no longer has added value

**Comment by yonahforst** [comment]
please use 0.2.7. there was an android bug in 0.2.6

**Pull request merged**
