### PR TITLE
Improved error handling for "Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])'" on com.zoontek.rnpermissions.RNPermissionsModule.onRequestPermissionsResult

### PR DESCRIPTION
**Pull request by webraptor**
# Summary

This PR further extends on some crash reports that we've seen for android users in production environments, which were already handled and reduced in occurrences by https://github.com/zoontek/react-native-permissions/pull/805 and https://github.com/zoontek/react-native-permissions/commit/63b695a609c1fb00b7611d98e7b4658e816d8788

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] tested in live/production environment using PRs fork as source

### CODE REVIEW

**Comment by webraptor** [comment]
@zoontek any idea when you could look into this PR?

**Comment by zoontek** [comment]
@webraptor I think it would be better to simplify it to only this (and catch all exceptions, without custom messages are the Exception `e` details are logged anyway):

```java
try {
  mCallbacks.get(requestCode).invoke(grantResults, getPermissionAwareActivity());
  mCallbacks.remove(requestCode);
  return mCallbacks.size() == 0;
} catch (Exception e) {
  FLog.e(
    "PermissionsModule",
    e,
    "Unexpected invocation of `onRequestPermissionsResult`");
  return false;
}
```

**Comment by webraptor** [comment]
Yeah @zoontek, that would work as well. Wasn't sure if anyone else might want the more detailed exception catching. 

I'll update the PR shortly so it's easier to merge.

**Comment by webraptor** [comment]
PR code updated

**Comment by webraptor** [comment]
@zoontek PR code updated. Thanks

**Comment by zoontek** [comment]
@webraptor Thanks, I will have a look and release this weekend.

**Comment by zoontek** [comment]
Sorry, I was not personally available (at least had no free time) until now. I merge this is a `4.1.0` for more testing before a release, thanks a lot!

**Comment by zoontek** [comment]
Done, thanks! https://github.com/zoontek/react-native-permissions/releases/tag/4.1.0

**Pull request merged**
