### PR TITLE
Local network permission

### PR DESCRIPTION
**Pull request by kikimaxs**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I added a sample use of the API in the example project (`example/App.tsx`)

### CODE REVIEW

**Comment by zoontek** [comment]
@kikimaxs Please rebase and keep the changes as **minimal** as possible.

**Comment by zoontek** [comment]
It appears this PR is copy / pasted from https://github.com/zoontek/react-native-permissions/pull/687. Probably an issue with a fork where you tried to merge it.

**Comment by knro** [comment]
Any hopes of rebasing this and merging it?

**Comment by zoontek** [comment]
@knro Read the conversation on the original pull request: https://github.com/zoontek/react-native-permissions/pull/687#issuecomment-1243016366

**Pull request closed without merging**
