### PR TITLE
Adding placeholder file so Android doesn't crash on require statement

### LINKED ISSUE #5: Add js file for Android so it doesn't crash
I'm attempting to use this module along with react-native-android-permissions, the issue is that requiring this module throws the following error.

screenshot 2016-06-02 14 09 01

I've forked and fixed it by adding a `ReactNativePermissions.android.js` as placeholder.

Would you accept a PR?

### PR DESCRIPTION
**Pull request by corymsmith**
Fixes #5

### CODE REVIEW

**Comment by yonahforst** [comment]
great! thank you

**Comment by corymsmith** [comment]
@yonahforst No worries, any plans for an update to the NPM version?

**Comment by yonahforst** [comment]
hecho! done

**Comment by corymsmith** [comment]
Perfect! Thank you sir

**Pull request merged**
