### PR TITLE
Fix flow error (#230)

### PR DESCRIPTION
**Pull request by josephbuchma**
Fix for #230

### CODE REVIEW

**Comment by zoontek** [comment]
By doing this, you import both versions on both platforms.

**Comment by josephbuchma** [comment]
Well, yeah, it probably should be handled by flow properly. Until then this works around without noticeable issues.

**Comment by ErikAlfredsson** [comment]
Running into the same issue. Any progress on this, or a possible workaround I can do on my side while waiting for this to be fixed and merged?

**Comment by remew** [comment]
I think that to add `permissions.js.flow` is better solution.
I tried to add it in `MY_PROJECT/node_modules/react-native-permissions/lib/` and run `flow` then no errors found.

**Comment by remew** [comment]
@ErikAlfredsson
How is this?
1. Add `'.*/node_modules/react-native-permissions/'` to `.flowconfig`'s `[ignore]` section
1. Install `flow-typed` (`npm install -g flow-typed`)
1. Run `flow-typed create-stub react-native-permissions` 
1. Edit `YOUR_PROJECT/flow-typed/npm/react-native-permissions_vx.x.x.js` for type definition

**Comment by cvongrim** [comment]
@remew What did you edit in `YOUR_PROJECT/flow-typed/npm/react-native-permissions_vx.x.x.js` file?

I think I figured it out. This is what I updated mine to look like.

```
declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module './lib/permissions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/index' {
  declare module.exports: $Exports<'react-native-permissions'>;
}
declare module 'react-native-permissions/index.js' {
  declare module.exports: $Exports<'react-native-permissions'>;
}```

**Comment by remew** [comment]
@cvongrim I declared `ReactNativePermissions` interface and some types in that file like below.

```javascript
declare module 'react-native-permissions' {
  // these types are required by ReactNativePermissions interface.
  declare type Status = 'authorized' | 'denied' | 'restricted' | 'undetermined';
  declare type Rationale = {title: string, message: string};
  declare type CheckOptions = string | {type: string};
  declare type RequestOptions = string | {type: string, rationale?: Rationale};

  // lib/permissions.(ios|android).js are exporting different implementation class.
  // but they have same name methods.
  declare interface ReactNativePermissions {
    canOpenSettings(): Promise<boolean>;
    openSettings(): Promise<*>;
    getTypes(): Array<string>;
    check(permission: string, options?: CheckOptions): Promise<Status>;
    request(permission: string, options?: RequestOptions): Promise<Status>;
    checkMultiple(permissions: Array<string>): Promise<{ [string]: string }>;
  }

  declare module.exports: ReactNativePermissions;
}
```

**Comment by xtrycatchx** [comment]
Optionally (or temporarily), for apps using this library they can optionally use this in their flowconfig files

```Javascript
[untyped]
.*/node_modules/react-native-permissions
```

**Comment by zoontek** [comment]
It's now available in the 1.2.0! Please check the changelog https://github.com/react-native-community/react-native-permissions/releases/tag/1.2.0

**Pull request closed without merging**
