### PR TITLE
Motion permission request

### PR DESCRIPTION
**Pull request by jkimbo**
Add code to request CoreMotion permission

(Btw I am not an Objective-C developer so I might have got things very wrong. It seems to work in my app and most of the code if inspired from https://github.com/iosphere/ISHPermissionKit/blob/master/ISHPermissionKit/Requests/ISHPermissionRequestMotion.m)

### CODE REVIEW

**Comment by TylerM89** [comment]
Can we get this merged? This is very useful.

**Comment by TylerM89** [comment]
@zoontek can we merge this?

**Comment by zoontek** [comment]
@acenth Unfortunatelly it has conflicts. Maybe @jkimbo can fix them.

**Comment by peterlau** [comment]
All credit due to jkimbo, but in the interest of time I took his branch and got it to work (i believe) on top of the latest master

https://github.com/yonahforst/react-native-permissions/pull/210

**Comment by jkimbo** [comment]
Thanks @peterlau ! I'll close this PR in favour of https://github.com/yonahforst/react-native-permissions/pull/210

**Comment by peterlau** [comment]
Thanks for merging. Looking forward to next release on npm.

**Pull request closed without merging**
