### PR TITLE
4.0.0 - iOS 17 and Android 14 support

### LINKED ISSUE #804: Calendar permission fail on iOS 17 (will be released on Sept 18th)
### Bug summary

In new iOS 17 (to be relased on 18th of Sept)
this permission request: https://github.com/zoontek/react-native-permissions/blob/33472788eac2526276477afd077b50f3a0855371/ios/Calendars/RNPermissionHandlerCalendars.m#L31
is deprecated and throw error: 
`Error: -requestAccessToEntityType:completion: has been deprecated-calling this method is no longer allowed. Instead, use -requestFullAccessToEventsWithCompletion:, -requestWriteOnlyAccessToEventsWithCompletion:, or -requestFullAccessToRemindersWithCompletion:.`

Deprication notice: https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccesstoentitytype

### Library version

3.9.0

### Environment info

```shell
ios 17
```

### Steps to reproduce

request calendar permissions on iOS 17

### Reproducible sample code

```js
`await request(PERMISSIONS.IOS.CALENDARS);`
```

### PR DESCRIPTION
**Pull request by zoontek**
Hi folks 👋

This PR has been opened to track the development of the next major version, targeting iOS 17 and Android 14.
Note that this version **requires Xcode 15** to work.

## TODO

- [x] Rename `BluetoothPeripheral` permission into `Bluetooth`
- [x] Drop support for React Native < 0.70, iOS < 12.4
- [x] Remove the React Native CLI plugin
- [x] Remove permission handlers podspecs
- [x] Add Android `READ_MEDIA_VISUAL_USER_SELECTED` permission
- [x] Add support for new iOS calendar / reminders full access permissions (fixes #804)
- [x] Add support for iOS calendar write only permission
- [x] Migrate the `flagAsRequested` helper inside the FaceID permission

But maybe there's more?  I'm not really aware of the privacy changes in the next iOS / Android versions (don't hesitate to comment about it 🙂)

## Future features

You may have noticed that there are numerous open feature requests in the issues.

The reason is simple: maintaining this library takes time, and it's not an easy task, especially with new OS releases and privacy-focused changes (which is a positive thing) happening each year.

Lately I discussed with some companies, many of them expressed a desire for these features but were uncertain about how to help since writing code for a React Native library can be challenging for non-native developers 😕

If your company is interested in a particular feature, please reach out to me and request a quote (at my freelancing rate). Once it's developed and merged, sure it will be made available to everyone, but you won't have to pay for maintenance.

This is a way of contributing to open source 💸

#### Features I would like to implement:

- https://github.com/zoontek/react-native-permissions/issues/229
- https://github.com/zoontek/react-native-permissions/issues/490
- https://github.com/zoontek/react-native-permissions/issues/509
- https://github.com/zoontek/react-native-permissions/issues/527
- https://github.com/zoontek/react-native-permissions/issues/689
- https://github.com/zoontek/react-native-permissions/issues/795
- https://github.com/zoontek/react-native-permissions/issues/800

7zfmog

## How to try it

Install the `@next` version:

```sh
$ npm install --save react-native-permissions@next
# --- or ---
$ yarn add react-native-permissions@next
```

### CODE REVIEW

**Comment by egealpay** [comment]
Do we have an estimated time for merge?

**Comment by zoontek** [comment]
@egealpay No. But you can use it (`@next` on npm), give feedbacks here, it will sure help secure the release 🙂!

**Comment by egealpay** [comment]
@zoontek I can, but is it possible for you to give priority to SCHEDULE_EXACT_ALARM permission feature?

**Comment by zoontek** [comment]
@egealpay sure, can your company help?

**Comment by johanmic** [comment]
I'm getting the `No podspec found for Permission-Camera` bug when trying to install @next
https://github.com/zoontek/react-native-permissions/issues/812

**Comment by zoontek** [comment]
@johanmic That's normal.

Screenshot 2023-10-11 at 14 30 03

**Comment by zoontek** [comment]
For companies seeking to help, I put 4 feature requests on https://polar.sh/zoontek (a collaborative open source funding platform):

- https://github.com/zoontek/react-native-permissions/issues/490
- https://github.com/zoontek/react-native-permissions/issues/509
- https://github.com/zoontek/react-native-permissions/issues/527
- https://github.com/zoontek/react-native-permissions/issues/689

Now let's see 😄

**Comment by chichilatte** [comment]
Many thanks to @zoontek for your invaluable work ❤️ 

We have a React Native 0.66.5 project which this module no longer supports since v4.0.0 (everything below RN 0.70 has been dropped, yikes). I made [a patch](https://gist.github.com/chichilatte/ff61bb53a7e032c5a487653a4247e311) for `react-native-permissions@3.10.1` that cherrypicks from this PR the fix for the ATT issue ([#823](https://github.com/zoontek/react-native-permissions/issues/823)). Useful to anyone trying to get their app through the App Store review process. Ours was rejected until we applied the patch.

**Pull request merged**
