### PR TITLE
Bring back openSettings on android

### PR DESCRIPTION
**Pull request by kevinresol**
I know there are other library could do that. But for API completeness I think it should be included.

Another option is to remove the API for ios altogether.

### CODE REVIEW

**Comment by YahyaBagia** [comment]
For those who are finding a way to open App Settings on Android, this is how I have managed to do so. And so far it works well.

I have used [react-native-android-open-settings](https://github.com/levelasquez/react-native-android-open-settings) to open App Settings when permission is denied on Android.

```
//IMPORT ON TOP OF SCREEN
import {Alert, Platform} from 'react-native';
import AndroidOpenSettings from 'react-native-android-open-settings'


//WHEN PERMISSION IS DENIED BY USER
Alert.alert('Permission required', 'Grant Camera, Storage, Location, et.c.. permission',
   [
      {text: 'Open Settings', onPress: async () => {
          if(Platform.OS === 'ios'){
            await Permissions.openSettings();
          }else{
            AndroidOpenSettings.appDetailsSettings()
          }
      }},
      {text: 'Dismiss', onPress: () => {
          console.log('USER DOES NOT WISH TO OPEN SETTINGS TO GRANT PERMISSION');
      }, style: 'cancel'}
   ],
);

```

**Comment by rendomnet** [comment]
@kevinresol What are additional setup steps when using this commit in React Native?

**Comment by adirzoari** [comment]
@rendomnet @joenoon @corymsmith @YahyaBagia  how do you handle after user back from open settings and allow location? any callback??

**Comment by zoontek** [comment]
@adirzoari You can use AppState to detect that the app switch to foreground.

**Comment by YahyaBagia** [comment]
@adirzoari  I haven't tried it. As far as I remember, iOS app restarts every-time we change permission from app settings. Don't know how android handles permission change.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).

**Pull request closed without merging**
