### PR TITLE
Add ATT workaround to docs

### PR DESCRIPTION
**Pull request by thewirv**
# Summary
Added workaround for App Tracking Transperency on iOS 15.0 to the documentation.

Motivation: ... as discussed in [this comment](https://github.com/zoontek/react-native-permissions/issues/648#issuecomment-933461300)

## Test Plan

No testing needed, only docs have changed.

## Checklist

- [ ] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by zoontek** [comment]
You have been to fast! Check my comment: https://github.com/zoontek/react-native-permissions/issues/648#issuecomment-943397384

I suggest avoiding the wording "workaround" here since it's the correct behavior: Your app must be active to request ATT. A workaround is more of a temporary solution until the issue is properly fixed.

**Comment by mikehardy** [comment]
:-) too fast is a good problem to have, but kudos for taking my not-that-gentle nudge for a PR and doing it :-) :champagne:

**Comment by thewirv** [comment]
@mikehardy Sure, I mean this is how Open Source works, and I can't stand people who are just complaining, without the thought of actually helping out ever occuring to them.

@zoontek Do you think it would make sense to say something in the vein of, "ATT permissions should be requested when the App becomes active because requesting it on mount can lead to problems," or do you think the explanation is not necessary?

**Comment by zoontek** [comment]
@TheWirv Instead of "on mount can lead to problems", you can say that "if the app is not active, the request prompt will not appear". Problems is a bit too vague

**Comment by zoontek** [comment]
I merge it and will add a few changes since I want it to be in the README for the next release (npm one is not synced with GitHub README). Thanks a lot 🙂

**Comment by thewirv** [comment]
Hey @zoontek, sorry, I spaced out there for a moment. I 100% agree with your points, but thanks for merging anyway. :)

**Pull request merged**
