### PR TITLE
fix: export PERMISSIONS

### PR DESCRIPTION
**Pull request by 1natsu172**
# Summary

The `PERMISSIONS` that were exported in v2 are not exported in v3. Specifically, the PERMISSIONS object is exported, but the actual object is empty.

This causes an error when migrating from v2 because the permission constants are not found.

In this PR, the `PERMISSIONS` exported from each OS file has been removed and integrated into `permission.ts`.

## Test Plan

* Check the `PERMISSIONS` exported from each OS file is not used from anywhere.
* ran
	* `yarn run lint`
	* `yarn run format`
	* `yarn run tscheck`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by zoontek** [comment]
@1natsu172 I'm not sure to understand what this PR really fix. Exporting empty maps on other platforms is something we want to avoid bundling unnecessary permissions.

Ex: The permission list on windows weights ~8ko. There's no need to put that in the iOS or the Android JS bundle.

**Comment by 1natsu172** [comment]
@zoontek Sorry about that. I've been using the constants of each OS for test assertions in jest.

I meant that the automatic resolution of "platform-specific extensions" by metro is not possible in jest, so can't get the constants in the node runtime. So I tried to export it with this PR.

However, I also really understood your point about not doing unnecessary platform bundling.

What do you think of the idea of not exporting from `src/permissions.ts` but exporting the constants for each platform for testing from `mock.js`? If you agree, will modify this PR.

**Comment by zoontek** [comment]
@1natsu172 I agree, only the mock needs to be edited.

```js
// mock.js
const {PERMISSIONS: {ANDROID}} = require('./dist/commonjs/permissions.android');
const {PERMISSIONS: {IOS}} = require('./dist/commonjs/permissions.ios');
const {PERMISSIONS: {WINDOWS}} = require('./dist/commonjs/permissions.windows');

const {RESULTS} = require('./dist/commonjs/results');

const PERMISSIONS = {ANDROID, IOS, WINDOWS};
export {PERMISSIONS, RESULTS};

// …
```

This should work. I don't want to export `ANDROID`, `IOS` or `WINDOWS` directly from the module, as this makes no sense / it's no clear to use in a codebase.

**Comment by 1natsu172** [comment]
@zoontek Thank you. I just changed the PR content to `mock.js` and re-committed. Please check it.

**Comment by zoontek** [comment]
LGTM 👍

**Comment by zoontek** [comment]
I made a new release for it: https://github.com/zoontek/react-native-permissions/releases/tag/3.0.5

**Comment by 1natsu172** [comment]
@zoontek Thanks for the very very fast release! 🚀

**Pull request merged**
